DROP TABLE Osoba CASCADE CONSTRAINTS;


CREATE TABLE Osoba(
RodneCislo Number NOT NULL PRIMARY KEY,
Meno VARCHAR2(25) NOT NULL,
Priezvisko VARCHAR2(25) NOT NULL,
Narodnost VARCHAR(25) NOT NULL,
DatumNarodenia Date NOT NULL
);

CREATE TABLE Hrac(
Prezyvka VARCHAR2(25) NOT NULL,
Hra Number NOT NULL ,
Vybavenie Number NOT NULL ,
Klan Number NOT NULL ,
CONSTRAINT Hrac_Hra_FK FOREIGN KEY (Hra) REFERENCES Hra,
CONSTRAINT Hrac_Vybaenie_FK FOREIGN KEY (Vybavenie) REFERENCES Vybavenie,
CONSTRAINT Hrac_Klan_FK FOREIGN KEY (Klan) REFERENCES Klan


);

CREATE TABLE Vybavenie(
  ID NUMBER NOT NULL PRIMARY KEY,
  Mys VARCHAR2(25),
  Klavesnica VARCHAR2(25),
  GPU VARCHAR2(25),
  Sluchadla VARCHAR2(25)
);

CREATE TABLE Hra(
  ID NUMBER NOT NULL PRIMARY KEY,
  Zaner VARCHAR2(25),
  DatumVydania Date NOT NULL,
  HernyMod VARCHAR2(25),
  Vydavatelstvo VARCHAR2(25)

);

CREATE TABLE Klan(
  ID NUMBER NOT NULL PRIMARY KEY,
  Narodnost VARCHAR2(25),
  Hymna VARCHAR2(25),
  Logo VARCHAR2(25),
  VodcaKlanu VARCHAR2(25)
);

CREATE TABLE Tim(
  ID NUMBER NOT NULL PRIMARY KEY
);

CREATE TABLE Turnaj(
  ID NUMBER NOT NULL PRIMARY KEY
)